# Generated by Django 3.2.4 on 2021-09-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('a', 'Private and Luxury'), ('b', 'Full-day Tours'), ('c', 'Day trips')], max_length=50, verbose_name='Place Type'),
        ),
    ]
